//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelegramWebHook.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"با سلام و احترام
ربات تلگرامی کنترل محتوا برای مدیریت گروه های تلگرام نوشته شده است.
امکانات ربات:
1- امکان حذف لینک
2- امکان حذف پیام هایی که در جواب داده شده اند
3- امکان قفل گروه در ساعات مشخصی از شب برای ارامش  افراد
4- امکان حذف استیکر
5- امکان حذف فیلم
6- امکان حذف عکس
7- امکان حذف ربات به محض اضافه شدن به گروه
8- امکان حذف شخص اضافه کننده ربات
9- امکان حذف پیغام های فروارد شده از کانال
10- امکان پین کردن متن مشخص در ساعت خاص به صورت روزانه
11- امکان تعیین سقف روزانه پیام برای هر نفر
12 - امکان تعیین حداقل و حداکثر کاراکتر برای پیام
")]
        public string Message {
            get {
                return ((string)(this["Message"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ربات تلگرام به صورت موقت به مدت 3 روز برای شما فعال است. در صورت تمایل میتوانید م" +
            "دت را تمدید نمایید.")]
        public string MessageTempActivation {
            get {
                return ((string)(this["MessageTempActivation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("به علت عدم تمدید ربات، ربات کنترل محتوا برای این گروه غیر فعال شد، جهت کسب اطلاعا" +
            "ت بیشتر با مدیریت ربات صحبت کنید.")]
        public string MessageDeactivated {
            get {
                return ((string)(this["MessageDeactivated"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("مدت استفاده از ربات شما به اتمام رسیده است. لطفا ربات را تمدید نمایید.")]
        public string MessageExpired {
            get {
                return ((string)(this["MessageExpired"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Hour {
            get {
                return ((int)(this["Hour"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Minute {
            get {
                return ((int)(this["Minute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("لطفا نام کلید جدید را وارد نمایید.")]
        public string CreateNewButton {
            get {
                return ((string)(this["CreateNewButton"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("با سلام. به ربات خودرو خوش آمدید لطفا گزینه مد نظر خود را از لیست انتخاب نمایید.")]
        public string WelcomeMessage {
            get {
                return ((string)(this["WelcomeMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("لطفا نام کلید جدیدی برای این کلید وارد نمایید.")]
        public string EditButton {
            get {
                return ((string)(this["EditButton"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("لطفا نام کلید خود را وارد نمایید.")]
        public string CreateNewLinkButton {
            get {
                return ((string)(this["CreateNewLinkButton"]));
            }
        }
    }
}
